title: <p align="center"> Prahlad Siwakoti </p>

# logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  Pennsylvania, USA
  <br> +1(225)210-0199
  <br> prasiwakoti@gmail.com
  <br> <a href="pdf/resume_v1_DE.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/prahlad-siwakoti/">LinkedIn</a> |
  <a href="https://github.com/siwa-p">GitHub</a>
  <br> <a href="https://scholar.google.com/citations?user=ZUcAvcsAAAAJ&hl=en&oi=ao">Google Scholar</a> |
  </p>
  
  <p align="justify">
  I am a <b>data scientist</b> who enjoys finding patterns in the data and solving problems. 
  <br>
  I have graduated with a <b>Master's Degree in Data Science at University of Texas at Austin</b>, where I received training in data science fundamentals.
  <br>
  I am currently enrolled in <b>Data Engineering Apprenticeship</b> at Nashville Software School learning the fundamental of data engineering and good coding practices.

  I have a PhD in physics from Louisiana State University</b>.
  <br>
  I consider myself a hardworking, and inquisitive person. Details matter to me. I am easy to work with. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
# google_analytics: UA-145578661-1 # Google Analytics tracking ID

